[pytest]
addopts = 
	--doctest-modules
	--doctest-continue-on-failure
	--nbval
	--ignore='setup.py'
norecursedirs = 
	build
	dist
	.egg-info
	.cache
	.git
	course_modules/2_USDA_MyMarketNews_MATLAB_exported.ipynb
	htmlcov
	tmps